language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=django==1.4.20
  - DJANGO=django==1.5.12
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.7
  - DJANGO=django==1.8
install:
  - pip install $DJANGO
  - pip install -r requirements.txt
# Test behave_django with behave :)
script: python manage.py behave
matrix:
  exclude:
   - python: "3.3"
     env: DJANGO=django==1.4.20
   - python: "3.4"
     env: DJANGO=django==1.4.20
